training_title: MONTH-TOPIC
# The name of the repository (e.g., 2020-may-training)
# We use training-specific-template to help with development
repository: training-specific-template
# Full URL to the repository
# Again, using training-specific-template to aid in development
repository-url: https://github.com/AlexsLemonade/training-specific-template
start-date: YYYY-MM-DD
end-date: YYYY-MM-DD
# Specific release in AlexsLemonade/training-modules
# We use master to make development easier
release-tag: master
# The Docker user will almost always be ccdl, which is why this is here
docker-user: ccdl
docker-repo: DOCKER-REPOSITORY
docker-tag: DOCKER-TAG
# These are for loading Docker images from a file; only relevant for in-person
docker-targz: ccdl_docker_image.tar.gz
docker-tar: ccdl_docker_image.tar
# The image ID and size can be obtained by running `docker images` once you have a copy of the correct image for the training
docker-image-id: IMAGEID
docker-size: SIZE
# How we have historically distributed materials in-person
training-zip: TRAINING-ZIP
training-unzip-folder: TRAINING-UNZIP-FOLDER
